server:
  port: 9090
  servlet:
    async:
      request-timeout: 60000
spring:
  application:
    name: ms-app-nisum
  datasource:
    url: jdbc:h2:mem:nisumdb
    driverClassName: org.h2.Driver
    username: sa
    password: 

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
    
logging:
  config: classpath:logging/logback.xml
